name: Generate Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set filename
        id: report
        run: |
          echo "::set-output name=report_file_name::fga-eps-mds-${{ github.event.repository.name }}-$(TZ='America/Sao_Paulo' date +'%m-%d-%Y-%H:%M:%S')-${{ github.ref_name }}"

      - name: Get SonarCloud metrics
        run: |
          wget $SONAR_URL -O ${{ steps.report.outputs.report_file_name }}.json
        env:
          SONAR_URL: ${{ secrets.SONAR_URL }}

      - name: Pushes sonar file
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
        with:
          source_file: ${{ steps.report.outputs.report_file_name }}.json
          destination_repo: 'fga-eps-mds/2022-1-EuPescador-Doc'
          destination_folder: 'analytics-raw-data'
          user_email: ${{ secrets.GIT_EMAIL}}
          user_name: ${{ secrets.GIT_USER }}
          commit_message: Upload a new metrics from ${{ github.event.repository.name }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.tag_version.outputs.changelog }}
          prerelease: true
          artifacts: ${{ steps.report.outputs.report_file_name }}.json
